services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: helloStore
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  minio:
    image: minio/minio
    container_name: local-minio
    restart: always
    ports:
      - "9000:9000"   # 数据访问端口
      - "9001:9001"   # Web 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: qxxpdada
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: "mongodb://root:secret@mongodb:27017/helloStore?authSource=admin"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  minio_data: