version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: helloStore
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: "mongodb://root:secret@mongodb:27017/helloStore?authSource=admin"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
