spring.application.name=hello-store-service
spring.profiles.active=bromine

spring.data.mongodb.uri=mongodb://root:secret@10.0.0.210:27017/helloStore?authSource=admin

minio.url=http://127.0.0.1:9000
minio.access-key=minioadmin
minio.secret-key=qxxpdada
minio.bucket=hello-store

jwt.secret=tOaR@#8ZD7p6&#ZSQGW&ltJx5G%@t#yFJkxJDV&I@p0##JcwT#O9rcr*364r6Zd59S5ycTMQ%92WA*1dR#jFrju7JnF8ya4sn27k^%%i9&PRcW@4VxKerHyqCG2U$0Ab^cEmderCOonH^OhG#R1GuKd$^v%2Zp&3i76zH@%t7YGfw$x&%k!pDIo0Q^e3$x^tFIVBE9T*R25&iBpn6OP8S^xeMTASDeft5hbd$YCY2Ph@9fNZl#1UwH&IXpBAELLL
jwt.expiration-millis=86400000

